cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
  - vendor/
  - node_modules/

laravel_clean:
  stage: clean
  script:
    - "./clean_mysql.sh $DB_USERNAME $DB_PASSWORD $DB_DATABASE"

laravel_build:
  stage: build
  script:
    - "composer install"
    - "curl -o- -L https://yarnpkg.com/install.sh | bash"
    - "php artisan key:generate"
    - "php artisan clear-compiled"
    - "yarn install"
    - "cd node_modules/semantic-ui; gulp build; cd ../..;"
    - "gulp"
  artifacts:
    paths:
    - bootstrap/cache/
    - public/build
    - public/css
    - public/fonts
    - public/images
    - public/js
    expire_in: 1 hour

laravel_test:
  stage: test
  script:
    - "php artisan config:cache"
    - "php artisan migrate --env=testing"
    - "php artisan db:seed --env=testing"
    - "php artisan halo5:batch-metadata"
    - "gulp"
    - "./vendor/bin/phpunit --colors=never"
  dependencies:
  - laravel_build

laravel_deploy_production:
  stage: deploy
  environment: production
  script:
    - "curl -LO https://deployer.org/deployer.phar"
    - "php deployer.phar deploy production -vvv"
  only:
  - production

stages:
  - clean
  - build
  - test
  - deploy